#! /bin/bash

kvm_path=/mnt/DD1/kvm/osx/OSX-KVM
sudo virsh nodedev-detach pci_0000_08_00_0
sudo virsh nodedev-detach pci_0000_08_00_1
bash $kvm_path/br-setup.sh
sudo virsh start win10
if ! $(nc -zv 127.0.0.1 24800 > /dev/null 2>&1)
then
        nohup barrier /home/hexa/barrier.conf > /dev/null 2>&1 &
fi
one
